version: "3"
services:

  app:
    container_name: app
    restart: always
    build: .
    environment:
      - FLASK_ENV=docker
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - neo4j
    entrypoint:
      - /app/entrypoint.sh
    env_file: .env

  neo4j:
    image: neo4j:latest
    ports:
      - 17474:7474
      - 16477:6477
      - 17687:7687
    environment:
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - ./db/dbms:/data/dbms
